const { JSDOM } = require('jsdom');
const fs = require('fs');
const root = 'C:/Users/Administrator/Documents/Deepseek/前沿技术研究';
let html = fs.readFileSync(root + '/index.html', 'utf8');
html = html.replace('<script src="data.js"></script>', '<script>' + fs.readFileSync(root + '/data.js', 'utf8') + '</script>');
html = html.replace('<script src="js/app.js"></script>', '<script>' + fs.readFileSync(root + '/js/app.js', 'utf8') + '</script>');
const dom = new JSDOM(html, { url: 'http://localhost/', runScripts: 'dangerously', pretendToBeVisual: true });
const { window } = dom;
const errors = [];
window.onerror = function (m, s, l) { errors.push(String(m) + ' @' + l); };
window.IntersectionObserver = class { constructor(cb){} observe(){} unobserve(){} disconnect(){} };
window.HTMLElement.prototype.scrollIntoView = function () {};
window.matchMedia = function () { return { matches: false }; };
(async () => {
  await new Promise(r => setTimeout(r, 400));
  const d = window.document;
  d.getElementById('btnWeb').click();
  await new Promise(r => setTimeout(r, 80));
  d.querySelector('[data-action="open-tech"][data-id="T01"]').click();
  await new Promise(r => setTimeout(r, 60));
  d.querySelector('#panelBody .tab[data-name="assess"]').click();
  await new Promise(r => setTimeout(r, 40));
  const pane = d.querySelector('#panelBody .tabpane[data-name="assess"]');
  const txt = pane.textContent;
  console.log('蜘蛛图含 svg:', !!pane.querySelector('svg'));
  console.log('已去掉「本年度」字样:', !txt.includes('本年度'));
  console.log('图例 div 数量(应为 0):', pane.querySelectorAll('svg + div').length);
  console.log('错误:', errors.length ? errors.join(' || ') : '无');
})().catch(e => console.log('FATAL', e && e.stack));
